/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DefaultLayout: typeof import('./src/components/layouts/DefaultLayout.vue')['default']
    LayoutWrapper: typeof import('./src/components/layouts/LayoutWrapper.vue')['default']
    MinimalLayout: typeof import('./src/components/layouts/MinimalLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCard: typeof import('./src/components/TheCard.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheModalWindow: typeof import('./src/components/TheModalWindow.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
  }
}
